language: node_js

node_js:
  - '10.6.0'

sudo: required
addons:
  chrome: stable

cache:
  directories:
    - node_modules

script:
  - cd bpmn-flows && npm install && yarn build-prod

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start